import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Customnavbar from "./components/Customnavbar";
import { toast, ToastContainer } from "react-toastify";

import UserProvider from "@/context/userProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  
      {/* <h1>Header</h1> */}
        
          <UserProvider>
          <ToastContainer/>
          <Customnavbar/>
          <div className="m-2">{children}</div> 
          
          </UserProvider>
        
        {/* <h1>Footer</h1> */}
      </body>
    </html>
  );
}
